-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        edwin_bdita = {
            id = "edwin_bdita",
            horiz_adv_x = 1000,
            units_per_em = 1000,
            ascent = 736,
            descent = -264,
            glyphs = nil,
        }
    }
)
