-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        opensanscondensed_lightitalic = {
            id = "opensanscondensed_lightitalic",
            horiz_adv_x = 1229,
            units_per_em = 2048,
            ascent = 1638,
            descent = -410,
            glyphs = nil,
        }
    }
)
