-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        texgyreadventor_regular = {
            id = "texgyreadventor_regular",
            horiz_adv_x = 740,
            units_per_em = 1000,
            ascent = 808,
            descent = -192,
            glyphs = nil,
        }
    }
)
