-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        texgyreadventor_bolditalic = {
            id = "texgyreadventor_bolditalic",
            horiz_adv_x = 640,
            units_per_em = 1000,
            ascent = 815,
            descent = -185,
            glyphs = nil,
        }
    }
)
