-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        oldstandardtt_regular = {
            id = "oldstandardtt_regular",
            horiz_adv_x = 500,
            units_per_em = 1000,
            ascent = 762,
            descent = -238,
            glyphs = nil,
        }
    }
)
