-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        veggieburger = {
            id = "veggieburger",
            horiz_adv_x = 442,
            units_per_em = 1000,
            ascent = 820,
            descent = -180,
            glyphs = nil,
        }
    }
)
