-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        solveigdemibold = {
            id = "solveigdemibold",
            horiz_adv_x = 416,
            units_per_em = 1000,
            ascent = 716,
            descent = -284,
            glyphs = nil,
        }
    }
)
