-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        josefinslab_thin = {
            id = "josefinslab_thin",
            horiz_adv_x = 244,
            units_per_em = 1000,
            ascent = 750,
            descent = -250,
            glyphs = nil,
        }
    }
)
