-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        konstytucyja = {
            id = "konstytucyja",
            horiz_adv_x = 333,
            units_per_em = 1000,
            ascent = 581,
            descent = -419,
            glyphs = nil,
        }
    }
)
