-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        rougescript_regular = {
            id = "rougescript_regular",
            horiz_adv_x = 462,
            units_per_em = 1250,
            ascent = 1000,
            descent = -250,
            glyphs = nil,
        }
    }
)
