-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        carrelectronicdingbats = {
            id = "carrelectronicdingbats",
            horiz_adv_x = 4223,
            units_per_em = 4096,
            ascent = 3276,
            descent = -820,
            glyphs = nil,
        }
    }
)
