-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        bitstreamverasansmono_bold = {
            id = "bitstreamverasansmono_bold",
            horiz_adv_x = 1233,
            units_per_em = 2048,
            ascent = 1556,
            descent = -492,
            glyphs = nil,
        }
    }
)
