-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        toms_newroman = {
            id = "toms_newroman",
            horiz_adv_x = 364,
            units_per_em = 1000,
            ascent = 800,
            descent = -200,
            glyphs = nil,
        }
    }
)
