-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        leaguegothic_condensed = {
            id = "leaguegothic_condensed",
            horiz_adv_x = 232,
            units_per_em = 1000,
            ascent = 735,
            descent = -265,
            glyphs = nil,
        }
    }
)
