-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        kawoszeh = {
            id = "kawoszeh",
            horiz_adv_x = 543,
            units_per_em = 1000,
            ascent = 740,
            descent = -260,
            glyphs = nil,
        }
    }
)
