-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        fixedersys1x = {
            id = "fixedersys1x",
            horiz_adv_x = 800,
            units_per_em = 1600,
            ascent = 1300,
            descent = -300,
            glyphs = nil,
        }
    }
)
