-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        pinball_data = {
            id = "pinball_data",
            horiz_adv_x = 542,
            units_per_em = 1000,
            ascent = 800,
            descent = -200,
            glyphs = nil,
        }
    }
)
