-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        mplus1p_extrabold = {
            id = "mplus1p_extrabold",
            horiz_adv_x = 1000,
            units_per_em = 1000,
            ascent = 860,
            descent = -140,
            glyphs = nil,
        }
    }
)
