-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        znikomitno24 = {
            id = "znikomitno24",
            horiz_adv_x = 1110,
            units_per_em = 2000,
            ascent = 1520,
            descent = -480,
            glyphs = nil,
        }
    }
)
