-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        windsong = {
            id = "windsong",
            horiz_adv_x = 388,
            units_per_em = 1500,
            ascent = 1200,
            descent = -300,
            glyphs = nil,
        }
    }
)
