-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        pixelcode_thinitalic = {
            id = "pixelcode_thinitalic",
            horiz_adv_x = 672,
            units_per_em = 1008,
            ascent = 806,
            descent = -202,
            glyphs = nil,
        }
    }
)
