-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        goudystm_italic = {
            id = "goudystm_italic",
            horiz_adv_x = 327,
            units_per_em = 1000,
            ascent = 777,
            descent = -223,
            glyphs = nil,
        }
    }
)
