-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        lato_black = {
            id = "lato_black",
            horiz_adv_x = 1160,
            units_per_em = 2000,
            ascent = 1610,
            descent = -390,
            glyphs = nil,
        }
    }
)
