-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        aileron_semibolditalic = {
            id = "aileron_semibolditalic",
            horiz_adv_x = 601,
            units_per_em = 1000,
            ascent = 770,
            descent = -230,
            glyphs = nil,
        }
    }
)
