-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        fantasquesansmono_bold = {
            id = "fantasquesansmono_bold",
            horiz_adv_x = 1060,
            units_per_em = 2048,
            ascent = 1650,
            descent = -398,
            glyphs = nil,
        }
    }
)
