-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        princesssofia = {
            id = "princesssofia",
            horiz_adv_x = 796,
            units_per_em = 1024,
            ascent = 819,
            descent = -205,
            glyphs = nil,
        }
    }
)
