-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        baskervville_italic = {
            id = "baskervville_italic",
            horiz_adv_x = 870,
            units_per_em = 1000,
            ascent = 710,
            descent = -290,
            glyphs = nil,
        }
    }
)
