-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        printbold = {
            id = "printbold",
            horiz_adv_x = 412,
            units_per_em = 1000,
            ascent = 755,
            descent = -245,
            glyphs = nil,
        }
    }
)
