-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        deutsch_gothic = {
            id = "deutsch_gothic",
            horiz_adv_x = 276,
            units_per_em = 940,
            ascent = 752,
            descent = -188,
            glyphs = nil,
        }
    }
)
