-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        slabo27px_regular = {
            id = "slabo27px_regular",
            horiz_adv_x = 420,
            units_per_em = 810,
            ascent = 648,
            descent = -162,
            glyphs = nil,
        }
    }
)
