-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        signika_bold = {
            id = "signika_bold",
            horiz_adv_x = 1956,
            units_per_em = 2000,
            ascent = 1600,
            descent = -400,
            glyphs = nil,
        }
    }
)
