-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        ostrichsans_black = {
            id = "ostrichsans_black",
            horiz_adv_x = 1705,
            units_per_em = 2048,
            ascent = 1536,
            descent = -512,
            glyphs = nil,
        }
    }
)
