-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        rechtmanplain = {
            id = "rechtmanplain",
            horiz_adv_x = 190,
            units_per_em = 1600,
            ascent = 1100,
            descent = -500,
            glyphs = nil,
        }
    }
)
