-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        fixedersyslight2x = {
            id = "fixedersyslight2x",
            horiz_adv_x = 1600,
            units_per_em = 3200,
            ascent = 2600,
            descent = -600,
            glyphs = nil,
        }
    }
)
