-- Auto-generated by font2lua - DO NOT EDIT!
-- For font license and info, see: https://github.com/gmlewis/go-fonts/
local F = require("font_library")

F:addFonts(
    {
        latoregular = {
            id = "latoregular",
            horiz_adv_x = 1187,
            units_per_em = 2048,
            ascent = 1649,
            descent = -399,
            glyphs = nil,
        }
    }
)
